/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DesktopIndexRouteImport } from './routes/desktop.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DesktopSettingsRouteImport } from './routes/desktop.settings'
import { Route as DesktopProjectIdRouteImport } from './routes/desktop.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const DesktopIndexRoute = DesktopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesktopRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const DesktopSettingsRoute = DesktopSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopProjectIdRoute = DesktopProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => DesktopRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desktop': typeof DesktopRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/desktop/$projectId': typeof DesktopProjectIdRoute
  '/desktop/settings': typeof DesktopSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/desktop/': typeof DesktopIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/desktop/$projectId': typeof DesktopProjectIdRoute
  '/desktop/settings': typeof DesktopSettingsRoute
  '/desktop': typeof DesktopIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desktop': typeof DesktopRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/desktop/$projectId': typeof DesktopProjectIdRoute
  '/desktop/settings': typeof DesktopSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/desktop/': typeof DesktopIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desktop'
    | '/login'
    | '/projects'
    | '/desktop/$projectId'
    | '/desktop/settings'
    | '/projects/$projectId'
    | '/desktop/'
    | '/projects/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/desktop/$projectId'
    | '/desktop/settings'
    | '/desktop'
    | '/projects'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/desktop'
    | '/login'
    | '/projects'
    | '/desktop/$projectId'
    | '/desktop/settings'
    | '/projects/$projectId'
    | '/desktop/'
    | '/projects/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesktopRoute: typeof DesktopRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/desktop/': {
      id: '/desktop/'
      path: '/'
      fullPath: '/desktop/'
      preLoaderRoute: typeof DesktopIndexRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/desktop/settings': {
      id: '/desktop/settings'
      path: '/settings'
      fullPath: '/desktop/settings'
      preLoaderRoute: typeof DesktopSettingsRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/desktop/$projectId': {
      id: '/desktop/$projectId'
      path: '/$projectId'
      fullPath: '/desktop/$projectId'
      preLoaderRoute: typeof DesktopProjectIdRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface DesktopRouteChildren {
  DesktopProjectIdRoute: typeof DesktopProjectIdRoute
  DesktopSettingsRoute: typeof DesktopSettingsRoute
  DesktopIndexRoute: typeof DesktopIndexRoute
}

const DesktopRouteChildren: DesktopRouteChildren = {
  DesktopProjectIdRoute: DesktopProjectIdRoute,
  DesktopSettingsRoute: DesktopSettingsRoute,
  DesktopIndexRoute: DesktopIndexRoute,
}

const DesktopRouteWithChildren =
  DesktopRoute._addFileChildren(DesktopRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesktopRoute: DesktopRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
